Support kernels after 4.19.201.
d94d95ae0dd0 ("gro: ensure frag0 meets IP header alignment") added the
definition for skb_frag_off in a linux header, so no need to redefine it.

This fixes a build error when using v4.19.325-cip134 headers to build this
driver:

  In file included from /home/builder/rpmbuild/BUILD/intel-e1000e-3.8.7/src/e1000.h:14:0,
		   from /home/builder/rpmbuild/BUILD/intel-e1000e-3.8.7/src/param.c:8:
  /home/builder/rpmbuild/BUILD/intel-e1000e-3.8.7/src/kcompat.h:7138:28: error: redefinition of 'skb_frag_off'
   static inline unsigned int skb_frag_off(const skb_frag_t * frag)
			      ^
  In file included from ./include/linux/if_ether.h:23:0,
		   from ./include/uapi/linux/ethtool.h:19,
		   from ./include/linux/ethtool.h:18,
		   from ./include/linux/netdevice.h:41,
		   from /home/builder/rpmbuild/BUILD/intel-e1000e-3.8.7/src/param.c:4:
  ./include/linux/skbuff.h:2818:28: note: previous definition of 'skb_frag_off' was here
   static inline unsigned int skb_frag_off(const skb_frag_t *frag)

Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>