compat: support kernel > 4.19.291 (skb_frag_off).
d94d95ae0dd0 ("gro: ensure frag0 meets IP header alignment") added the
definition for skb_frag_off in a linux header, so no need to redefine it.

This fixes a build error when using v4.19.325-cip134 headers to build this
driver:

  /home/builder/rpmbuild/BUILD/igb-5.4.6/src/kcompat.h:7140:28: error: redefinition of 'skb_frag_off'
   static inline unsigned int skb_frag_off(const skb_frag_t *frag)
			      ^
  In file included from ./include/linux/tcp.h:21:0,
		   from ./include/net/tcp.h:24,
		   from /home/builder/rpmbuild/BUILD/igb-5.4.6/src/igb.h:12,
		   from /home/builder/rpmbuild/BUILD/igb-5.4.6/src/igb_debugfs.c:4:
  ./include/linux/skbuff.h:2818:28: note: previous definition of 'skb_frag_off' was here
   static inline unsigned int skb_frag_off(const skb_frag_t *frag)

Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>