intel-ixgbe-alt: compat: handle newer kernels with skb_frag_off defined.
d94d95ae0dd0 ("gro: ensure frag0 meets IP header alignment") added the
definition for skb_frag_off in a linux header, so no need to redefine it.

This fixes a build error when using v4.19.325-cip134 headers to build this
driver:

  In file included from /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/ixgbe_osdep.h:17:0,
		   from /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/ixgbe_type.h:45,
		   from /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/ixgbe_82598.c:4:
  /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/kcompat.h:7200:28: error: redefinition of 'skb_frag_off'
   static inline unsigned int skb_frag_off(const skb_frag_t *frag)
			      ^
  In file included from ./include/linux/if_ether.h:23:0,
		   from /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/ixgbe_osdep.h:15,
		   from /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/ixgbe_type.h:45,
		   from /home/builder/rpmbuild/BUILD/ixgbe-5.9.4/src/ixgbe_82598.c:4:
  ./include/linux/skbuff.h:2818:28: note: previous definition of 'skb_frag_off' was here
   static inline unsigned int skb_frag_off(const skb_frag_t *frag)

Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>